apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: tenant1-cluster-reader-binding
subjects:
  - kind: ServiceAccount
    name: tenant1-sa
    namespace: tenant1
roleRef:
  kind: ClusterRole
  name: tenant1-cluster-reader
  apiGroup: rbac.authorization.k8s.io
