apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: hpa-tenant1-noisy
  namespace: tenant1
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: tenant1-noisy  # the name of the deployment to scale
  minReplicas: 1
  maxReplicas: 5
  metrics:
  - type: Resource
    resource:
      name: cpu
      target:
        type: Utilization
        averageUtilization: 50  # scale up if average CPU usage is over 50%

---
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: hpa-tenant2-cpu-hog
  namespace: tenant1
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: tenant2-cpu-hog  # the name of the deployment to scale
  minReplicas: 1
  maxReplicas: 5
  metrics:
  - type: Resource
    resource:
      name: cpu
      target:
        type: Utilization
        averageUtilization: 50  # scale up if average CPU usage is over 50%
