apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  namespace: tenant2
  name: tenant-admin
rules:
  - apiGroups: [""]
    resources: ["pods", "services", "deployments"]
    verbs: ["get", "list", "create", "update", "delete"]
